server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare?characterEncoding=UTF8
    username: tensquare
    password: tensquare123
  jpa: 
    database: MySQL
    show-sql: true
